# arxivの学問領域の指定
subject: 'cat:eess.AS OR cat:eess.SP'

# 検索キーワード
keywords:
        source separation: 2
        independent vector extraction: 1
        dereverberation: 1
        online: 1
        Geometric Constraint: 1
        

# 通知の閾値
score_threshold: 3
