# arxivの学問領域の指定
subject: 'cat:eess.SP OR cat:eess.AS'

# 検索キーワード
keywords:
        IVE: 1        
        dereverberation: 1
        online: 1
        overdetermined: 1
        Geometric Constraint: 1
        

# 通知の閾値
score_threshold: 1
